Repository jenkins-x/test-infra, pull requests merged in 2019-07, with the labels that each got.

#13 feat: updating new master with CI/CD config'd
  Dockerfile
  OWNERS
  jenkins-x.yml
  prow/OWNERS
  prow/artifact-uploader/OWNERS
  prow/clonerefs/OWNERS
  prow/cluster/OWNERS
  prow/cmd/artifact-uploader/OWNERS
  prow/cmd/branchprotector/OWNERS
  prow/cmd/build/OWNERS
  prow/cmd/checkconfig/OWNERS
  prow/cmd/clonerefs/OWNERS
  prow/cmd/config-bootstrapper/OWNERS
  prow/cmd/crier/OWNERS
  prow/cmd/deck/OWNERS
  prow/cmd/entrypoint/OWNERS
  prow/cmd/gcsupload/OWNERS
  prow/cmd/gerrit/OWNERS
  prow/cmd/hook/OWNERS
  prow/cmd/horologium/OWNERS
  prow/cmd/initupload/OWNERS
  prow/cmd/jenkins-operator/OWNERS
  prow/cmd/mkbuild-cluster/OWNERS
  prow/cmd/mkpj/OWNERS
  prow/cmd/mkpod/OWNERS
  prow/cmd/peribolos/OWNERS
  prow/cmd/phony/OWNERS
  prow/cmd/plank/OWNERS
  prow/cmd/sidecar/OWNERS
  prow/cmd/sinker/OWNERS
  prow/cmd/status-reconciler/OWNERS
  prow/cmd/tide/OWNERS
  prow/cmd/tot/OWNERS
  prow/crier/OWNERS
  prow/deck/OWNERS
  prow/entrypoint/OWNERS
  prow/external-plugins/cherrypicker/OWNERS
  prow/external-plugins/refresh/OWNERS
  prow/gcsupload/OWNERS
  prow/gerrit/OWNERS
  prow/hook/OWNERS
  prow/initupload/OWNERS
  prow/jenkins/OWNERS
  prow/phony/OWNERS
  prow/plank/OWNERS
  prow/pod-utils/OWNERS
  prow/pubsub/OWNERS
  prow/push.sh
  prow/sidecar/OWNERS
  prow/spyglass/OWNERS
  prow/statusreconciler/OWNERS
  prow/tide/OWNERS
Labels: lgtm, size/XXL

#15 feat: Support metapipeline
  prow/cmd/pipeline/controller.go
  prow/cmd/pipeline/controller_test.go
Labels: approved, lgtm, size/L

#16 fix: update jenkins-x.yaml with valid path for kaniko secret
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#17 fix: Make sure test case runs are ordered
  prow/cmd/pipeline/controller.go
  prow/cmd/pipeline/controller_test.go
Labels: approved, size/M
